"""empty message

Revision ID: b71ee951ae4e
Revises: 
Create Date: 2025-03-09 03:41:21.724850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71ee951ae4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('referer', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['referer'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user__id'), 'user', ['_id'], unique=True)
    op.create_table('referal_system',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('owner_email', sa.Text(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_referal_system__id'), 'referal_system', ['_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referal_system__id'), table_name='referal_system')
    op.drop_table('referal_system')
    op.drop_index(op.f('ix_user__id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
