"""empty message

Revision ID: bdcf6e3d1b51
Revises: 
Create Date: 2025-02-19 23:57:30.164824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdcf6e3d1b51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('referer', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['referer'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user__id'), 'user', ['_id'], unique=True)
    op.create_table('referal_system',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.email'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referal_system')
    op.drop_index(op.f('ix_user__id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
